### ISSUE TITLE
Application script structure changed in Gradle 3.2, breaking this plugin.

### ISSUE THREAD

**Issue by tylerbenson** [Zoltu/application-agent-gradle-plugin#1]
Here's the legacy start script that this plugin works with:
https://github.com/gradle/gradle/blob/REL_2.14.1/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt

Here's the latest version that your regex doesn't like:
https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt

**Comment by MicahZoltu** [comment]
@tylerbenson Can you see if `v1.0.14` resolves your issue?  I think this change will fix it, but I'm bad and didn't test (I don't currently have a project that uses this plugin handy).

**Comment by tylerbenson** [comment]
Yeah, we tested and confirmed this does work.
